namespace Evie
{
    public enum EQClassEnum
    {
        None = 0,
        Warrior = 1,
        Cleric = 2,
        Paladin = 3,
        Ranger = 4,
        ShadowKnight = 5,
        Druid = 6,
        Monk = 7,
        Bard = 8,
        Rogue = 9,
        Shaman = 10,
        Necromancer = 11,
        Wizard = 12,
        Magician = 13,
        Enchanter = 14,
        Beastlord = 15,
        Berserker = 16,
        WarriorGM = 20,
        ClericGM = 21,
        PaladinGM = 22,
        RangerGM = 23,
        ShadowKnightGM = 24,
        DruidGM = 25,
        MonkGM = 26,
        BardGM = 27,
        RogueGM = 28,
        ShamanGM = 29,
        NecromancerGM = 30,
        WizardGM = 31,
        MagicianGM = 32,
        EnchanterGM = 33,
        BeastlordGM = 34,
        BerserkerGM = 35,
        Banker = 40,
        Merchant = 41,
        DiscordMerchant = 59,
        AdventureRecruiter = 60,
        AdventureMerchant = 61,
        LDoNTreasure = 62,
        TributeMaster = 63,
        GuildTributeMaster = 64,
        GuildBanker = 66,
        NorrathsKeepersMerchant = 67,
        DarkReignMerchant = 68,
        FellowshipMaster = 69,
        AlternateCurrencyMerchant = 70,
    }
}
