namespace Evie
{
    public enum EQSpellEffect : int
    {
        CurrentHP = 0, // implemented - Heals and nukes, repeates every tic if in a buff
        ArmorClass = 1, // implemented
        ATK = 2, // implemented
        MovementSpeed = 3, // implemented - SoW, SoC, etc
        STR = 4, // implemented
        DEX = 5, // implemented
        AGI = 6, // implemented
        STA = 7, // implemented
        INT = 8, // implemented
        WIS = 9, // implemented
        CHA = 10, // implemented - used as a spacer
        AttackSpeed = 11, // implemented
        Invisibility = 12, // implemented - TO DO: Implemented Invisiblity Levels
        SeeInvis = 13, // implemented - TO DO: Implemented See Invisiblity Levels
        WaterBreathing = 14, // implemented
        CurrentMana = 15, // implemented
        NPCFrenzy = 16, // not used
        NPCAwareness = 17, // not used
        Lull = 18, // implemented - Reaction Radius
        AddFaction = 19, // implemented - Alliance line
        Blind = 20, // implemented
        Stun = 21, // implemented
        Charm = 22, // implemented
        Fear = 23, // implemented
        Stamina = 24, // implemented - Invigor and such
        BindAffinity = 25, // implemented - TO DO: Implement 2nd and 3rd Recall (value 2,3 ect). Sets additional bind points.
        Gate = 26, // implemented - Gate to bind point
        CancelMagic = 27, // implemented
        InvisVsUndead = 28, // implemented
        InvisVsAnimals = 29, // implemented
        ChangeFrenzyRad = 30, // implemented - Pacify
        Mez = 31, // implemented
        SummonItem = 32, // implemented
        SummonPet = 33, // implemented
        Confuse = 34, // not used (Nimbus of Temporal Rifting) ?
        DiseaseCounter = 35, // implemented
        PoisonCounter = 36, // implemented
        DetectHostile = 37, // not used
        DetectMagic = 38, // not used
        TwinCastBlocker = 39, // implemented - If present in spell, then the spell can not be twincast.
        DivineAura = 40, // implemented
        Destroy = 41, // implemented - Disintegrate, Banishment of Shadows
        ShadowStep = 42, // implemented
        Berserk = 43, // implemented (*not used in any known live spell) Makes client 'Berserk' giving crip blow chance.
        Lycanthropy = 44, // implemented
        Vampirism = 45, // implemented (*not used in any known live spell) Stackable lifetap from melee.
        ResistFire = 46, // implemented
        ResistCold = 47, // implemented
        ResistPoison = 48, // implemented
        ResistDisease = 49, // implemented
        ResistMagic = 50, // implemented
        DetectTraps = 51, // not used
        SenseDead = 52, // implemented
        SenseSummoned = 53, // implemented
        SenseAnimals = 54, // implemented
        Rune = 55, // implemented
        TrueNorth = 56, // implemented
        Levitate = 57, // implemented
        Illusion = 58, // implemented
        DamageShield = 59, // implemented
        TransferItem = 60, // not used
        Identify = 61, // implemented
        ItemID = 62, // not used
        WipeHateList = 63, // implemented, @Memblur, chance to wipe hate list of target, base: pct chance, limit: none, max: ? (not implemented), Note: caster level and CHA add to pct chance
        SpinTarget = 64, // implemented - TO DO: Not sure stun portion is working correctly
        InfraVision = 65, // implemented
        UltraVision = 66, // implemented
        EyeOfZomm = 67, // implemented
        ReclaimPet = 68, // implemented
        TotalHP = 69, // implemented
        CorpseBomb = 70, // not used
        NecPet = 71, // implemented
        PreserveCorpse = 72, // not used
        BindSight = 73, // implemented, @Vision, see through the eyes of your target, click off buff to end effect, base: 1, limit: none, max: none
        FeignDeath = 74, // implemented
        VoiceGraft = 75, // implemented
        Sentinel = 76, // *not implemented?(just seems to send a message)
        LocateCorpse = 77, // implemented
        AbsorbMagicAtt = 78, // implemented - Rune for spells
        CurrentHPOnce = 79, // implemented - Heals and nukes, non-repeating if in a buff
        EnchantLight = 80, // not used
        Revive = 81, // implemented - Resurrect
        SummonPC = 82, // implemented
        Teleport = 83, // implemented
        TossUp = 84, // implemented - Gravity Flux
        WeaponProc = 85, // implemented - i.e. Call of Fire
        Harmony = 86, // implemented
        MagnifyVision = 87, // implemented - Telescope
        Succor = 88, // implemented - Evacuate/Succor lines
        ModelSize = 89, // implemented - Shrink, Growth
        Cloak = 90, // *not implemented - Used in only 2 spells
        SummonCorpse = 91, // implemented
        InstantHate = 92, // implemented - add hate
        StopRain = 93, // implemented - Wake of Karana
        NegateIfCombat = 94, // implemented
        Sacrifice = 95, // implemented
        Silence = 96, // implemented
        ManaPool = 97, // implemented
        AttackSpeed2 = 98, // implemented - Melody of Ervaj
        Root = 99, // implemented
        HealOverTime = 100, // implemented
        CompleteHeal = 101, // implemented
        Fearless = 102, // implemented - Valiant Companion
        CallPet = 103, // implemented - Summon Companion
        Translocate = 104, // implemented
        AntiGate = 105, // implemented - Translocational Anchor
        SummonBSTPet = 106, // implemented
        AlterNPCLevel = 107, // implemented - not used on live
        Familiar = 108, // implemented
        SummonItemIntoBag = 109, // implemented - summons stuff into container
        IncreaseArchery = 110, // implemented
        ResistAll = 111, // implemented - Note: Physical Resists are not modified by this effect.
        CastingLevel = 112, // implemented
        SummonHorse = 113, // implemented
        ChangeAggro = 114, // implemented - Hate modifing buffs(ie horrifying visage)
        Hunger = 115, // implemented - Song of Sustenance
        CurseCounter = 116, // implemented
        MagicWeapon = 117, // implemented - makes weapon magical
        Amplification = 118, // implemented, @Song, stackable singing mod, base: mod%, limit: none, max: none, Note: Can focus itself.
        AttackSpeed3 = 119, // implemented
        HealRate = 120, // implemented - reduces healing by a %
        ReverseDS = 121, // implemented
        ReduceSkill = 122, // implemented - base: skill id, limit: none, max: none, formula: % skill is reduced (positive)
        Screech = 123, // implemented Spell Blocker(If have buff with value +1 will block any effect with -1)
        ImprovedDamage = 124, // implemented
        ImprovedHeal = 125, // implemented
        SpellResistReduction = 126, // implemented
        IncreaseSpellHaste = 127, // implemented, @Fc, On Caster, cast time mod pct, base: pct
        IncreaseSpellDuration = 128, // implemented, @Fc, On Caster, spell duration mod pct, base: pct
        IncreaseRange = 129, // implemented, @Fc, On Caster, spell range mod pct, base: pct
        SpellHateMod = 130, // implemented, @Fc, On Caster, spell hate mod pct, base: min pct, limit: max pct
        ReduceReagentCost = 131, // implemented, @Fc, On Caster, do not consume reagent pct chance, base: min pct, limit: max pct
        ReduceManaCost = 132, // implemented, @Fc, On Caster, reduce mana cost by pct, base: min pct, limt: max pct
        FcStunTimeMod = 133, // implemented, @Fc, On Caster, spell range mod pct, base: pct
        LimitMaxLevel = 134, // implemented, @Ff, Max level of spell that can be focused, if base2 then decrease effectiviness by base2 % per level over max, base: lv, base2: effectiveness pct
        LimitResist = 135, // implemented, @Ff, Resist Type(s) that a spell focus can require or exclude, base1: resist type, Include: Positive Exclude: Negative
        LimitTarget = 136, // implemented, @Ff, Target Type(s) that a spell focus can require or exclude, base1: target type, Include: Positive Exclude: Negative
        LimitEffect = 137, // implemented, @Ff, Spell effect(s) that a spell focus can require or exclude, base1: SPA id, Include: Positive Exclude: Negative
        LimitSpellType = 138, // implemented, @Ff, Only allow focus spells that are Beneficial or Detrimental, base1: 0=det 1=bene
        LimitSpell = 139, // implemented, @Ff, Specific spell id(s) that a spell focus can require or exclude, base1: SPA id, Include: Positive Exclude: Negative
        LimitMinDur = 140, // implemented, @Ff, Mininum duration of spell that can be focused, base1: tics
        LimitInstant = 141, // implemented, @Ff, Include or exclude if an isntant cast spell can be focused, base1: 0=Exclude if Instant 1=Allow only if Instant
        LimitMinLevel = 142, // implemented, @Ff, Mininum level of spell that can be focused, base1: lv
        LimitCastTimeMin = 143, // implemented, @Ff, Mininum cast time of spell that can be focused, base1: milliseconds
        LimitCastTimeMax = 144, // implemented, @Ff, Max cast time of spell that can be focused, base1: milliseconds
        Teleport2 = 145, // implemented - Banishment of the Pantheon
        ElectricityResist = 146, // *not implemented TODO: Now used on live, xyz for teleport spells? also in temp pets?
        PercentalHeal = 147, // implemented
        StackingCommand_Block = 148, // implemented?
        StackingCommand_Overwrite = 149, // implemented?
        DeathSave = 150, // implemented
        SuspendPet = 151, // implemented, @Pet, allow caster to have an extra suspended pet, base: 0=no buffs/items 1=buffs+items, limit: none, max: none
        TemporaryPets = 152, // implemented
        BalanceHP = 153, // implemented
        DispelDetrimental = 154, // implemented, @Dispel, removes only detrimental effects on a target, base: pct chance (950=95%), limit: none, max: none
        SpellCritDmgIncrease = 155, // implemented - no known live spells use this currently
        IllusionCopy = 156, // implemented - Deception
        SpellDamageShield = 157, // implemented, @DS, causes non-melee damage on caster of a spell, base: Amt DS (negative), limit: none, max: unknown (same as base but +)
        Reflect = 158, // implemented, @SpellMisc, reflect casted detrimental spell back at caster, base: chance pct, limit: resist modifier (positive value reduces resists), max: pct of base dmg mod (50=50pct of base)
        AllStats = 159, // implemented
        MakeDrunk = 160, // *not implemented - Effect works entirely client side (Should check against tolerance)
        MitigateSpellDamage = 161, // implemented, @Runes, mitigate incoming spell damage by percentage until rune fades, base: percent mitigation, limit: max dmg absorbed per hit, max: rune amt, Note: If placed on item or AA, will provide stackable percent mitigation.
        MitigateMeleeDamage = 162, // implemented - rune with max value
        NegateAttacks = 163, // implemented
        AppraiseLDonChest = 164, // implemented
        DisarmLDoNTrap = 165, // implemented
        UnlockLDoNChest = 166, // implemented
        PetPowerIncrease = 167, // implemented, @Fc, On Caster, pet power mod, base: value
        MeleeMitigation = 168, // implemented
        CriticalHitChance = 169, // implemented
        SpellCritChance = 170, // implemented
        CrippBlowChance = 171, // implemented
        AvoidMeleeChance = 172, // implemented
        RiposteChance = 173, // implemented
        DodgeChance = 174, // implemented
        ParryChance = 175, // implemented
        DualWieldChance = 176, // implemented
        DoubleAttackChance = 177, // implemented
        MeleeLifetap = 178, // implemented
        AllInstrumentMod = 179, // implemented, @Song, set mod for ALL instrument/singing skills that will be used if higher then item mods, base: mod%, limit: none, max: none
        ResistSpellChance = 180, // implemented
        ResistFearChance = 181, // implemented
        HundredHands = 182, // implemented
        MeleeSkillCheck = 183, // implemented
        HitChance = 184, // implemented
        DamageModifier = 185, // implemented
        MinDamageModifier = 186, // implemented
        BalanceMana = 187, // implemented - Balances party mana
        IncreaseBlockChance = 188, // implemented
        CurrentEndurance = 189, // implemented
        EndurancePool = 190, // implemented
        Amnesia = 191, // implemented - Silence vs Melee Effect
        Hate = 192, // implemented - Instant and hate over time.
        SkillAttack = 193, // implemented,
        FadingMemories = 194, // implemented, @Aggro, Remove from hate lists and make invisible. Can set max level of NPCs that can be affected. base: success chance, limit: max level (ROF2), max: max level (modern client), Note: Support for max level requires Rule (Spells, UseFadingMemoriesMaxLevel) to be true. If used from limit field, then it set as the level, ie. max level of 75 would use limit value of 75. If set from max field, max level 75 would use max value of 1075, if you want to set it so it checks a level range above the spell target then for it to only work on mobs 5 levels or below you set max value to 5.
        StunResist = 195, // implemented
        StrikeThrough = 196, // implemented
        SkillDamageTaken = 197, // implemented
        CurrentEnduranceOnce = 198, // implemented
        Taunt = 199, // implemented - % chance to taunt the target
        ProcChance = 200, // implemented
        RangedProc = 201, // implemented
        IllusionOther = 202, // implemented - Project Illusion
        MassGroupBuff = 203, // implemented
        GroupFearImmunity = 204, // implemented - (Does not use bonus)
        Rampage = 205, // implemented, @Combat Instant, Perform a primary slot combat rounds on all creatures within a 40 foot radius, base: number of attack rounds, limit: max entities hit per round, max: none, Note: AE range is 40 by default. Custom: Set field 'aoe_range' to override default. Adding additional attacks and hit count limit.
        AETaunt = 206, // implemented
        FleshToBone = 207, // implemented
        PurgePoison = 208, // not used
        DispelBeneficial = 209, // implemented, @Dispel, removes only beneficial effects on a target, base: pct chance (950=95%), limit: none, max: none
        PetShield = 210, // implmented, @ShieldAbility, allows pet to 'shield' owner for 50 pct of damage taken for a duration, base: Time multiplier 1=12 seconds, 2=24 ect, limit: mitigation on pet owner override (not on live), max: mitigation on pet overide (not on live)
        AEMelee = 211, // implemented TO DO: Implement to allow NPC use (client only atm).
        FrenziedDevastation = 212, // implemented - increase spell criticals + all DD spells cast 2x mana.
        PetMaxHP = 213, // implemented[AA] - increases the maximum hit points of your pet
        MaxHPChange = 214, // implemented
        PetAvoidance = 215, // implemented[AA] - increases pet ability to avoid melee damage
        Accuracy = 216, // implemented
        HeadShot = 217, // implemented - ability to head shot (base2 = damage)
        PetCriticalHit = 218, // implemented[AA] - gives pets a baseline critical hit chance
        SlayUndead = 219, // implemented - Allow extra damage against undead (base1 = rate, base2 = damage mod).
        SkillDamageAmount = 220, // implemented
        Packrat = 221, // implemented as bonus
        BlockBehind = 222, // implemented - Chance to block from behind (with our without Shield)
        DoubleRiposte = 223, // implemented - Chance to double riposte [not used on live]
        GiveDoubleRiposte = 224, // implemented[AA]
        GiveDoubleAttack = 225, // implemented[AA] - Allow any class to double attack with set chance.
        TwoHandBash = 226, // *not implemented as bonus
        ReduceSkillTimer = 227, // implemented
        ReduceFallDamage = 228, // implented - reduce the damage that you take from falling
        PersistantCasting = 229, // implemented
        ExtendedShielding = 230, // implemented, @ShieldAbility, extends the range of your /shield ability by an amount of distance, base: distance units, limit: none, max: none
        StunBashChance = 231, // implemented - increase chance to stun from bash.
        DivineSave = 232, // implemented (base1 == % chance on death to insta-res) (base2 == spell cast on save)
        Metabolism = 233, // implemented - Modifies food/drink consumption rates.
        ReduceApplyPoisonTime = 234, // not implemented as bonus - reduces the time to apply poison
        ChannelChanceSpells = 235, // implemented[AA] - chance to channel from SPELLS *No longer used on live.
        FreePet = 236, // not used
        GivePetGroupTarget = 237, // implemented[AA] - (Pet Affinity)
        IllusionPersistence = 238, // implemented - lends persistence to your illusionary disguises, causing them to last until you die or the illusion is forcibly removed.
        FeignedCastOnChance = 239, // implemented - ability gives you an increasing chance for your feigned deaths to not be revealed by spells cast upon you.
        StringUnbreakable = 240, // not used [Likely related to above - you become immune to feign breaking on a resisted spell and have a good chance of feigning through a spell that successfully lands upon you.]
        ImprovedReclaimEnergy = 241, // implemented - increase the amount of mana returned to you when reclaiming your pet.
        IncreaseChanceMemwipe = 242, // implemented - @Memblur, increases the chance to wipe hate with memory blurr, base: chance pct, limit: none, max: none, Note: Mods final blur chance after other bonuses added.
        CharmBreakChance = 243, // implemented - Total Domination
        RootBreakChance = 244, // implemented[AA] reduce the chance that your root will break.
        TrapCircumvention = 245, // implemented, @Traps, decreases the chance that you will set off a trap when opening a chest or other similar container by percentage, base: chance modifer, limit: none, max: none
        SetBreathLevel = 246, // *not implemented as bonus
        RaiseSkillCap = 247, // implemented[AA] - adds skill over the skill cap.
        SecondaryForte = 248, // not implemented as bonus(gives you a 2nd specialize skill that can go past 50 to 100)
        SecondaryDmgInc = 249, // implemented[AA] Allows off hand weapon to recieve a damage bonus (Sinister Strikes)
        SpellProcChance = 250, // implemented - Increase chance to proc from melee proc spells (ie Spirit of Panther)
        ConsumeProjectile = 251, // implemented[AA] - chance to not consume an arrow (ConsumeProjectile = 100)
        FrontalBackstabChance = 252, // implemented[AA] - chance to perform a full damage backstab from front.
        FrontalBackstabMinDmg = 253, // implemented[AA] - allow a frontal backstab for mininum damage.
        Blank = 254, // implemented
        ShieldDuration = 255, // implemented, , @ShieldAbility, extends the duration of your /shield ability, base: seconds, limit: none, max: none
        ShroudofStealth = 256, // implemented
        PetDiscipline = 257, // not implemented as bonus - /pet hold - official name is GivePetHold
        TripleBackstab = 258, // implemented[AA] - chance to perform a triple backstab
        CombatStability = 259, // implemented[AA] - damage mitigation
        AddSingingMod = 260, // implemented, @Song, set mod for specific instrument/singing skills that will be used if higher then item mods, base: mod%, limit: ItemType ID, max: none
        SongModCap = 261, // implemented, @Song, raise max song modifier cap, base: amt, limit: none, max: none, Note: No longer used on live
        RaiseStatCap = 262, // implemented
        TradeSkillMastery = 263, // implemented - lets you raise more than one tradeskill above master.
        HastenedAASkill = 264, // implemented
        MasteryofPast = 265, // implemented[AA] - Spells less than effect values level can not be fizzled
        ExtraAttackChance = 266, // implemented, @OffBonus, gives your double attacks a percent chance to perform an extra attack with 2-handed primary weapon, base: chance, limit: amt attacks, max: none
        AddPetCommand = 267, // implemented - sets command base2 to base1
        ReduceTradeskillFail = 268, // implemented - reduces chance to fail with given tradeskill by a percent chance
        MaxBindWound = 269, // implemented[AA] - Increase max HP you can bind wound.
        BardSongRange = 270, // implemented, @Song, increase range of beneficial bard songs, base: mod%, limit: none, max: none , Note: example Sionachie's Crescendo
        BaseMovementSpeed = 271, // implemented[AA] - mods basemove speed, doesn't stack with other move mods
        CastingLevel2 = 272, // implemented
        CriticalDoTChance = 273, // implemented
        CriticalHealChance = 274, // implemented
        CriticalMend = 275, // implemented[AA] - chance to critical monk mend
        Ambidexterity = 276, // implemented[AA] - increase chance to duel weild by adding bonus 'skill'
        UnfailingDivinity = 277, // implemented[AA] - ability grants your Death Pact-type spells a second chance to successfully heal their target, also can cause said spells to do a portion of their healing value even on a complete failure.
        FinishingBlow = 278, // implemented[AA] - chance to do massive damage under 10% HP (base1 = chance, base2 = damage)
        Flurry = 279, // implemented
        PetFlurry = 280, // implemented[AA]
        FeignedMinion = 281, // implemented, ability allows you to instruct your pet to feign death via the '/pet feign' command, base: succeed chance, limit: none, max: none, Note: Only implemented as an AA.
        ImprovedBindWound = 282, // implemented[AA] - increase bind wound amount by percent.
        DoubleSpecialAttack = 283, // implemented[AA] - Chance to perform second special attack as monk
        LoHSetHeal = 284, // not used
        NimbleEvasion = 285, // *not implemented - base1 = 100 for max
        FcDamageAmt = 286, // implemented, @Fc, On Caster, spell damage mod flat amt, base: amt
        SpellDurationIncByTic = 287, // implemented, @Fc, SPA: 287, SpellEffect::SpellDurationIncByTic, = On Caster, spell buff duration mod, base: tics
        SkillAttackProc = 288, // implemented, @Procs, chance to cast a spell when using a skill, base: chance, limit: skill, max: spellid, note: if used in AA the spell id is set in aa_ranks spell field, chance is calculated as 100% = value 1000.
        CastOnFadeEffect = 289, // implemented - Triggers only if fades after natural duration.
        IncreaseRunSpeedCap = 290, // implemented[AA] - increases run speed over the hard cap
        Purify = 291, // implemented, @Dispel, remove up specified amount of detiremental spells, base: amt removed, limit: none, max: none, Note: excluding charm, fear, resurrection, and revival sickness
        StrikeThrough2 = 292, // implemented[AA] - increasing chance of bypassing an opponent's special defenses, such as dodge, block, parry, and riposte.
        FrontalStunResist = 293, // implemented[AA] - Reduce chance to be stunned from front. -- live descriptions sounds like this isn't limited to frontal anymore
        CriticalSpellChance = 294, // implemented - increase chance to critical hit and critical damage modifier.
        ReduceTimerSpecial = 295, // not used
        FcSpellVulnerability = 296, // implemented, @Fc, On Target, spell damage taken mod pct, base: min pct, limit: max pct
        FcDamageAmtIncoming = 297, // implemetned, @Fc, On Target, damage taken flat amt, base: amt
        ChangeHeight = 298, // implemented
        WakeTheDead = 299, // implemented, @Pets, summon one temporary pet from nearby corpses that last a set duration, base: none, limit: none, max: duration (seconds). Note: max range of corpse is 250.
        Doppelganger = 300, // implemented
        ArcheryDamageModifier = 301, // implemented[AA] - increase archery damage by percent
        FcDamagePctCrit = 302, // implemented, @Fc, On Caster, spell damage mod pct, base: min pct, limit: max pct, Note: applied after critical hits has been calculated.
        FcDamageAmtCrit = 303, // implemented, @Fc, On Caster, spell damage mod flat amt, base: amt
        OffhandRiposteFail = 304, // implemented as bonus - enemy cannot riposte offhand attacks
        MitigateDamageShield = 305, // implemented - off hand attacks only (Shielding Resistance)
        ArmyOfTheDead = 306, // implemented, @Pets, summon multiple temporary pets from nearby corpses that last a set duration, base: amount of corpses that a pet can summon from, limit: none, max: duration (seconds). Note: max range of corpse is 250.
        Appraisal = 307, // *not implemented Rogue AA - This ability allows you to estimate the selling price of an item you are holding on your cursor.
        ZoneSuspendMinion = 308, // implemented, @Pet, allow suspended pets to be resummoned upon zoning, base: 1, limit: none, max: none, Calc: Bool
        GateCastersBindpoint = 309, // implemented - Gate to casters bind point
        ReduceReuseTimer = 310, // implemented, @Fc, On Caster, spell and disc reuse time mod by amount, base: milliseconds
        LimitCombatSkills = 311, // implemented, @Ff, Include or exclude combat skills or procs from being focused, base1: 0=Exclude if proc 1=Allow only if proc.
        Sanctuary = 312, // implemented - Places caster at bottom hate list, effect fades if cast cast spell on targets other than self.
        ForageAdditionalItems = 313, // implemented[AA] - chance to forage additional items
        Invisibility2 = 314, // implemented - fixed duration invisible
        InvisVsUndead2 = 315, // implemented - fixed duration ITU
        ImprovedInvisAnimals = 316, // implemented
        ItemHPRegenCapIncrease = 317, // implemented[AA] - increases amount of health regen gained via items
        ItemManaRegenCapIncrease = 318, // implemented - increases amount of mana regen you can gain via items
        CriticalHealOverTime = 319, // implemented
        ShieldBlock = 320, // implemented - Block attacks with shield
        ReduceHate = 321, // implemented
        GateToHomeCity = 322, // implemented
        DefensiveProc = 323, // implemented
        HPToMana = 324, // implemented
        NoBreakAESneak = 325, // implemented[AA] - [AA Nerves of Steel] increasing chance to remain hidden when they are an indirect target of an AoE spell.
        SpellSlotIncrease = 326, // *not implemented as bonus - increases your spell slot availability
        MysticalAttune = 327, // implemented - increases amount of buffs that a player can have
        DelayDeath = 328, // implemented - increases how far you can fall below 0 hp before you die
        ManaAbsorbPercentDamage = 329, // implemented
        CriticalDamageMob = 330, // implemented
        Salvage = 331, // implemented - chance to recover items that would be destroyed in failed tradeskill combine
        SummonToCorpse = 332, // *not implemented AA - Call of the Wild (Druid/Shaman Res spell with no exp) TOOD: implement this.
        CastOnRuneFadeEffect = 333, // implemented
        BardAEDot = 334, // implemented
        BlockNextSpellFocus = 335, // implemented, @Fc, On Caster, chance to block next spell, base: chance
        IllusionaryTarget = 336, // not used
        PercentXPIncrease = 337, // implemented
        SummonAndResAllCorpses = 338, // implemented
        TriggerOnCast = 339, // implemented, @Fc, On Caster, cast on spell use, base: chance pct limit: spellid
        SpellTrigger = 340, // implemented - chance to trigger spell [Share rolls with 469] All base2 spells share roll chance, only 1 cast.
        ItemAttackCapIncrease = 341, // implemented[AA] - increases the maximum amount of attack you can gain from items.
        ImmuneFleeing = 342, // implemented - stop mob from fleeing
        InterruptCasting = 343, // implemented - % chance to interrupt spells being cast every tic. Cacophony (8272)
        ChannelChanceItems = 344, // implemented[AA] - chance to not have ITEM effects interrupted when you take damage.
        AssassinateLevel = 345, // implemented as bonus - AA Assisination max level to kill
        HeadShotLevel = 346, // implemented[AA] - HeadShot max level to kill
        DoubleRangedAttack = 347, // implemented - chance at an additional archery attack (consumes arrow)
        LimitManaMin = 348, // implemented, @Ff, Mininum mana of spell that can be focused, base1: mana amt
        ShieldEquipDmgMod = 349, // implemented[AA] Increase melee base damage (indirectly increasing hate) when wearing a shield.
        ManaBurn = 350, // implemented - Drains mana for damage/heal at a defined ratio up to a defined maximum amount of mana.
        PersistentEffect = 351, // *not implemented. creates a trap/totem that casts a spell (spell id + base1?) when anything comes near it. can probably make a beacon for this
        IncreaseTrapCount = 352, // *not implemented - looks to be some type of invulnerability? Test ITC (8755)
        AdditionalAura = 353, // *not implemented - allows use of more than 1 aura, aa effect
        DeactivateAllTraps = 354, // *not implemented - looks to be some type of invulnerability? Test DAT (8757)
        LearnTrap = 355, // *not implemented - looks to be some type of invulnerability? Test LT (8758)
        ChangeTriggerType = 356, // not used
        FcMute = 357, // implemented, @Fc, On Caster, prevents spell casting, base: chance pct
        CurrentManaOnce = 358, // implemented
        PassiveSenseTrap = 359, // *not implemented - Invulnerability (Brell's Blessing)
        ProcOnKillShot = 360, // implemented - a buff that has a base1 % to cast spell base2 when you kill a "challenging foe" base3 min level
        SpellOnDeath = 361, // implemented - casts spell on death of buffed
        PotionBeltSlots = 362, // *not implemented[AA] 'Quick Draw' expands the potion belt by one additional available item slot per rank.
        BandolierSlots = 363, // *not implemented[AA] 'Battle Ready' expands the bandolier by one additional save slot per rank.
        TripleAttackChance = 364, // implemented
        ProcOnSpellKillShot = 365, // implemented - chance to trigger a spell on kill when the kill is caused by a specific spell with this effect in it (10470 Venin)
        GroupShielding = 366, // *not implemented[AA] This gives you /shieldgroup
        SetBodyType = 367, // implemented - set body type of base1 so it can be affected by spells that are limited to that type (Plant, Animal, Undead, etc)
        FactionMod = 368, // *not implemented - increases faction with base1 (faction id, live won't match up w/ ours) by base2
        CorruptionCounter = 369, // implemented
        ResistCorruption = 370, // implemented
        AttackSpeed4 = 371, // implemented - stackable slow effect 'Inhibit Melee'
        ForageSkill = 372, // implemented[AA] Will increase the skill cap for those that have the Forage skill and grant the skill and raise the cap to those that do not.
        CastOnFadeEffectAlways = 373, // implemented - Triggers if fades after natural duration OR from rune/numhits fades.
        ApplyEffect = 374, // implemented
        DotCritDmgIncrease = 375, // implemented - Increase damage of DoT critical amount
        Fling = 376, // *not implemented - used in 2 test spells (12945 | Movement Test Spell 1)
        CastOnFadeEffectNPC = 377, // implemented - Triggers only if fades after natural duration (On live these are usually players spells that effect an NPC).
        SpellEffectResistChance = 378, // implemented - Increase chance to resist specific spell effect (base1=value, base2=spell effect id)
        ShadowStepDirectional = 379, // implemented - handled by client
        Knockdown = 380, // implemented - small knock back(handled by client)
        KnockTowardCaster = 381, // *not implemented (Call of Hither) knocks you back to caster (value) distance units infront
        NegateSpellEffect = 382, // implemented, @Debuff, negates specific spell effect benefits for the duration of the debuff and prevent non-duration spell effect from working, base: see NegateSpellEffecttype Enum, limit: SPA id, max: none
        SympatheticProc = 383, // implemented, @Fc, On Caster, cast on spell use, base: variable proc chance on cast time, limit: spellid
        Leap = 384, // implemented - Leap effect, ie stomping leap
        LimitSpellGroup = 385, // implemented, @Ff, Spell group(s) that a spell focus can require or exclude, base1: spellgroup id, Include: Positive Exclude: Negative
        CastOnCurer = 386, // implemented - Casts a spell on the person curing
        CastOnCure = 387, // implemented - Casts a spell on the cured person
        SummonCorpseZone = 388, // implemented - summons a corpse from any zone(nec AA)
        FcTimerRefresh = 389, // implemented, @Fc, On Caster, reset all recast timers, base: 1, Note: Applied from casted spells only
        FcTimerLockout = 390, // implemented, @Fc, On Caster, set a spell to be on recast timer, base: recast duration milliseconds, Note: Applied from casted spells only
        LimitManaMax = 391, // implemented, @Ff, Mininum mana of spell that can be focused, base1: mana amt
        FcHealAmt = 392, // implemented, @Fc, On Caster, spell healing mod flat amt, base: amt
        FcHealPctIncoming = 393, // implemented, @Fc, On Target, heal received mod pct, base: pct, limit: random max pct
        FcHealAmtIncoming = 394, // implemented, @Fc, On Target, heal received mod flat amt, base: amt
        FcHealPctCritIncoming = 395, // implemented, @Fc, On Target, heal received mod pct, base: pct, limit: random max pct
        FcHealAmtCrit = 396, // implemented, @Fc, On Caster, spell healing mod flat amt, base: amt
        PetMeleeMitigation = 397, // implemented[AA] - additional mitigation to your pets. Adds AC
        SwarmPetDuration = 398, // implemented - Affects the duration of swarm pets
        FcTwincast = 399, // implemented - cast 2 spells for every 1
        HealGroupFromMana = 400, // implemented - Drains mana and heals for each point of mana drained
        ManaDrainWithDmg = 401, // implemented - Deals damage based on the amount of mana drained
        EndDrainWithDmg = 402, // implemented - Deals damage for the amount of endurance drained
        LimitSpellClass = 403, // implemented, @Ff, 'Spell Category' using table field 'spell_class' that a spell focus can require or exclude, base1: category type, Include: Positive Exclude: Negative
        LimitSpellSubclass = 404, // implemented, @Ff, 'Spell Category Subclass' using table field 'spell_subclass' that a spell focus can require or exclude, base1: category type, Include: Positive Exclude: Negative
        TwoHandBluntBlock = 405, // implemented - chance to block attacks when using two hand blunt weapons (similiar to shield block)
        CastonNumHitFade = 406, // implemented - casts a spell when a buff fades due to its numhits being depleted
        CastonFocusEffect = 407, // implemented - casts a spell if focus limits are met (ie triggers when a focus effects is applied)
        LimitHPPercent = 408, // implemented - limited to a certain percent of your hp(ie heals up to 50%)
        LimitManaPercent = 409, // implemented - limited to a certain percent of your mana
        LimitEndPercent = 410, // implemented - limited to a certain percent of your end
        LimitClass = 411, // implemented, @Ff, Class(es) that can use the spell focus, base1: class(es), Note: The class value in dbase is +1 in relation to item class value, set as you would item for multiple classes
        LimitRace = 412, // implemented, @Ff, Race that can use the spell focus, base1: race, Note: not used in any known live spells. Use only single race at a time.
        FcBaseEffects = 413, // implemented, @Fc, On Caster, base spell effectiveness mod pct, base: pct
        LimitCastingSkill = 414, // implemented, @Ff, Spell and singing skills(s) that a spell focus can require or exclude, base1: skill id, Include: Positive Exclude: Negative
        FFItemClass = 415, // implemented, @Ff, Limits focuses to be applied only from item click. base1: item ItemType (-1 to include for all ItemTypes,-1000 to exclude clicks from getting the focus, or exclude specific SubTypes or Slots if set), limit: item SubType (-1 for all SubTypes), max: item Slots (bitmask of valid slots, -1 ALL slots), Note: not used on live. See comments in Mob::CalcFocusEffect for more details.
        ACv2 = 416, // implemented - New AC spell effect
        ManaRegen_v2 = 417, // implemented - New mana regen effect
        SkillDamageAmount2 = 418, // implemented - adds skill damage directly to certain attacks
        AddMeleeProc = 419, // implemented - Adds a proc
        FcLimitUse = 420, // implemented, @Fc, On Caster, numhits mod pct, base: pct, Note: not used in any known live spells
        FcIncreaseNumHits = 421, // implemented, @Fc, On Caster, numhits mod flat amt, base: amt
        LimitUseMin = 422, // implemented, @Ff Minium amount of numhits for a spell to be focused, base: numhit amt
        LimitUseType = 423, // implemented, = @Ff Focus will only affect if has this numhits type, base: numhit type
        GravityEffect = 424, // implemented - Pulls/pushes you toward/away the mob at a set pace
        Display = 425, // *not implemented - Illusion: Flying Dragon(21626)
        IncreaseExtTargetWindow = 426, // *not implmented[AA] - increases the capacity of your extended target window
        SkillProcAttempt = 427, // implemented - chance to proc when using a skill(ie taunt)
        LimitToSkill = 428, // implemented, @Procs, limits what combat skills will effect a skill proc, base: skill value, limit: none, max: none
        SkillProcSuccess = 429, // implemented - chance to proc when tje skill in use successfully fires.
        PostEffect = 430, // *not implemented - Fear of the Dark(27641) - Alters vision
        PostEffectData = 431, // *not implemented - Fear of the Dark(27641) - Alters vision
        ExpandMaxActiveTrophyBen = 432, // not used
        CriticalDotDecay = 433, // implemented - increase critical dot chance, effect decays based on level of spell it effects. (12266)
        CriticalHealDecay = 434, // implemented - increase critical heal chance, effect decays based on level of spell it effects.
        CriticalRegenDecay = 435, // implemented - increase critical heal over time chance, effect decays based on level of spell it effects.
        BeneficialCountDownHold = 436, // not used ( 23491 | ABTest Buff Hold)
        TeleporttoAnchor = 437, // *not implemented - Teleport Guild Hall Anchor(33099)
        TranslocatetoAnchor = 438, // *not implemented - Translocate Primary Anchor (27750)
        Assassinate = 439, // implemented[AA] - Assassinate damage
        FinishingBlowLvl = 440, // implemented[AA] - Sets the level Finishing blow can be triggered on an NPC
        DistanceRemoval = 441, // implemented - Buff is removed from target when target moves X amount of distance away from where initially hit.
        TriggerOnReqTarget = 442, // implemented, @SpellTrigger, triggers a spell when Target Requirement conditions are met (see enum SpellRestriction for IDs), base: spellid, limit: SpellRestriction ID, max: none, Note: Usually cast on a target
        TriggerOnReqCaster = 443, // implemented, @SpellTrigger, triggers a spell when Caster Requirement conditions are met (see enum SpellRestriction for IDs), base: spellid, limit: SpellRestriction ID, max: none, Note: Usually self only
        ImprovedTaunt = 444, // implemented - Locks Aggro On Caster and Decrease other Players Aggro by X% on NPC targets below level Y
        AddMercSlot = 445, // *not implemented[AA] - [Hero's Barracks] Allows you to conscript additional mercs.
        AStacker = 446, // implementet - bufff stacking blocker (26219 | Qirik's Watch)
        BStacker = 447, // implemented
        CStacker = 448, // implemented
        DStacker = 449, // implemented
        MitigateDotDamage = 450, // implemented, @Runes, mitigate incoming dot damage by percentage until rune fades, base: percent mitigation, limit: max dmg absorbed per hit, max: rune amt, Note: If placed on item or AA, will provide stackable percent mitigation.
        MeleeThresholdGuard = 451, // implemented Partial Melee Rune that only is lowered if melee hits are over X amount of damage
        SpellThresholdGuard = 452, // implemented Partial Spell Rune that only is lowered if spell hits are over X amount of damage
        TriggerMeleeThreshold = 453, // implemented Trigger effect on X amount of melee damage taken in a single hit
        TriggerSpellThreshold = 454, // implemented Trigger effect on X amount of spell damage taken in a single hit
        AddHatePct = 455, // implemented Modify total hate by %
        AddHateOverTimePct = 456, // implemented Modify total hate by % over time.
        ResourceTap = 457, // implemented Coverts a percent of dmg from dmg spells(DD/DoT) to hp/mana/end.
        FactionModPct = 458, // implemented Modifies faction gains and losses by percent.
        DamageModifier2 = 459, // implemented - Modifies melee damage by skill type
        Ff_Override_NotFocusable = 460, // implemented, @Fc, Allow spell to be focused event if flagged with 'not_focusable' in spell table, base: 1
        ImprovedDamage2 = 461, // implemented, @Fc, On Caster, spell damage mod pct, base: min pct, limit: max pct
        FcDamageAmt2 = 462, // implemented, @Fc, On Caster, spell damage mod flat amt, base: amt
        Shield_Target = 463, // implemented, Base1 % damage shielded on target
        PC_Pet_Rampage = 464, // implemented - Base1 % chance to do rampage for base2 % of damage each melee round
        PC_Pet_AE_Rampage = 465, // implemented - Base1 % chance to do AE rampage for base2 % of damage each melee round
        PC_Pet_Flurry_Chance = 466, // implemented - Base1 % chance to do flurry from double attack hit.
        DS_Mitigation_Amount = 467, // implemented - Modify incoming damage shield damage by a flat amount
        DS_Mitigation_Percentage = 468, // implemented - Modify incoming damage shield damage by percentage
        Chance_Best_in_Spell_Grp = 469, // implemented - Chance to cast highest scribed spell within a spell group. All base2 spells share roll chance, only 1 cast.
        Trigger_Best_in_Spell_Grp = 470, // implemented - Chance to cast highest scribed spell within a spell group. Each spell has own chance.
        Double_Melee_Round = 471, // implemented, @OffBonus, percent chance to repeat primary weapon round with a percent damage modifier, base: pct chance repeat, limit: pct dmg mod, max: none
        Buy_AA_Rank = 472, // implemented, @Special, Used in AA abilities that have Enable/Disable toggle. Spell on Disabled Rank has this effect in it, base: 1, limit: none, max: none, Note: This will not just buy an AA
        Double_Backstab_Front = 473, // implemented - Chance to double backstab from front
        Pet_Crit_Melee_Damage_Pct_Owner = 474, // implemenetd - Critical damage mod applied to pets from owner
        Trigger_Spell_Non_Item = 475, // implemented - Trigger spell on cast only if not from item click.
        Weapon_Stance = 476, // implemented, @Misc, Apply a specific spell buffs automatically depending 2Hander, Shield or Dual Wield is equipped, base: spellid, base: 0=2H 1=Shield 2=DW, max: none
        Hatelist_To_Top_Index = 477, // Implemented - Chance to be set to top of rampage list
        Hatelist_To_Tail_Index = 478, // Implemented - Chance to be set to bottom of rampage list
        Ff_Value_Min = 479, // implemented, @Ff, Minimum base value of a spell that can be focused, base: spells to be focused base1 value
        Ff_Value_Max = 480, // implemented, @Ff, Max base value of a spell that can be focused, base: spells to be focused base1 value
        Fc_Cast_Spell_On_Land = 481, // implemented, @Fc, On Target, cast spell if hit by spell, base: chance pct, limit: spellid
        Skill_Base_Damage_Mod = 482, // implemented, @OffBonus, modify base melee damage by percent, base: pct, limit: skill(-1=ALL), max: none
        Fc_Spell_Damage_Pct_IncomingPC = 483, // implemented, @Fc, On Target, spell damage taken mod pct, base: min pct, limit: max pct
        Fc_Spell_Damage_Amt_IncomingPC = 484, // implemented, @Fc, On Target, damage taken flat amt, base: amt
        Ff_CasterClass = 485, // implemented, @Ff, Caster of spell on target with a focus effect that is checked by incoming spells must be specified class(es). base1: class(es), Note: Set multiple classes same as would for items
        Ff_Same_Caster = 486, // implemented, @Ff, Caster of spell on target with a focus effect that is checked by incoming spells, base1: 0=Must be different caster 1=Must be same caster
        Extend_Tradeskill_Cap = 487, //
        Defender_Melee_Force_Pct_PC = 488, //
        Worn_Endurance_Regen_Cap = 489, // implemented, modify worn regen cap, base: amt, limit: none, max: none
        Ff_ReuseTimeMin = 490, // implemented, @Ff, Minimum recast time of a spell that can be focused, base: recast time
        Ff_ReuseTimeMax = 491, // implemented, @Ff, Max recast time of a spell that can be focused, base: recast time
        Ff_Endurance_Min = 492, // implemented, @Ff, Minimum endurance cost of a spell that can be focused, base: endurance cost
        Ff_Endurance_Max = 493, // implemented, @Ff, Max endurance cost of a spell that can be focused, base: endurance cost
        Pet_Add_Atk = 494, // implemented - Bonus on pet owner which gives their pet increased attack stat
        Ff_DurationMax = 495, // implemented, @Ff, Max duration of spell that can be focused, base: tics
        Critical_Melee_Damage_Mod_Max = 496, // implemented - increase or decrease by percent critical damage (not stackable)
        Ff_FocusCastProcNoBypass = 497, //
        AddExtraAttackPct_1h_Primary = 498, // implemented, @OffBonus, gives your double attacks a percent chance to perform an extra attack with 1-handed primary weapon, base: chance, limit: amt attacks, max: none
        AddExtraAttackPct_1h_Secondary = 499, //implemented, @OffBonus, gives your double attacks a percent chance to perform an extra attack with 1-handed secondary weapon, base: chance, limit: amt attacks, max: none
        Fc_CastTimeMod2 = 500, // implemented, @Fc, On Caster, cast time mod pct, base: pct, Note: Can reduce to instant cast
        Fc_CastTimeAmt = 501, // implemented, @Fc, On Caster, cast time mod flat amt, base: milliseconds, Note: Can reduce to instant cast
        Fearstun = 502, // implemented - Stun with a max level limit. Normal stun restrictions don't apply.
        Melee_Damage_Position_Mod = 503, // implemented, @OffBonus, modify melee damage by percent if done from Front or Behind opponent, base: pct, limit: 0=back 1=front, max: none
        Melee_Damage_Position_Amt = 504, // implemented, @OffBonus, modify melee damage by flat amount if done from Front or Behind opponent, base: amt, limit: 0=back 1=front, max: none
        Damage_Taken_Position_Mod = 505, // implemented, @DefBonus, modify melee damage by percent if dmg taken from Front or Behind, base: pct, limit: 0=back 1=front, max: none
        Damage_Taken_Position_Amt = 506, // implemented -@DefBonus, modify melee damage by flat amount if dmg taken from your Front or Behind, base: amt, limit: 0=back 1=front, max: none
        Fc_Amplify_Mod = 507, // implemented, @Fc, On Caster, damage-heal-dot mod pct, base: pct
        Fc_Amplify_Amt = 508, // implemented, @Fc, On Caster, damage-heal-dot mod flat amt, base: amt
        Health_Transfer = 509, // implemented - exchange health for damage or healing on a target. ie Lifeburn/Act of Valor
        Fc_ResistIncoming = 510, // implemented, @Fc, On Target, resist modifier, base: amt
        Ff_FocusTimerMin = 511, // implemented, @Ff, sets a recast time until focus can be used again, base: 1, limit: time ms, Note: ie. limit to 1 trigger every 1.5 seconds
        Proc_Timer_Modifier = 512, // implemented - limits procs per amount of a time based on timer value, base: 1, limit: time ms, Note:, ie limit to 1 proc every 55 seconds)
        Mana_Max_Percent = 513, //
        Endurance_Max_Percent = 514, //
        AC_Avoidance_Max_Percent = 515, // implemented - stackable avoidance modifier
        AC_Mitigation_Max_Percent = 516, // implemented - stackable defense modifier
        Attack_Offense_Max_Percent = 517, //
        Attack_Accuracy_Max_Percent = 518, // implemented - stackable accurary modifer
        Luck_Amount = 519, //
        Luck_Percent = 520, //
        Endurance_Absorb_Pct_Damage = 521, // implemented - Reduces % of Damage using Endurance, drains endurance at a ratio (ie. 0.05 Endurance per Hit Point)
        Instant_Mana_Pct = 522, // implemented - Increase/Decrease mana by percent of max mana
        Instant_Endurance_Pct = 523, // implemented - Increase/Decrease mana by percent of max endurance
        Duration_HP_Pct = 524, // implemented - Decrease Current Hit Points by % of Total Hit Points per Tick, up to a MAX per tick
        Duration_Mana_Pct = 525, // implemented - Decrease Current Mana by % of Total Mana per Tick, up to a MAX per tick
        Duration_Endurance_Pct = 526, // implemented - Decrease Current Endurance by % of Total Hit Points per Tick, up to a MAX per tick
    }
}
